import "./globals.css";
import type { Metadata } from "next";
import { Antonio, League_Spartan } from "next/font/google";

import Header from "./components/Header";

const antonio = Antonio({
  subsets: ["latin"],
  weight: "500",
  display: "swap",
  variable: "--font-antonio",
});

const spartan = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-spartan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${spartan.variable} ${antonio.variable}`}>
      <body>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
